package com.sparta.delivery.product.presentation.dto.request;

import jakarta.validation.constraints.*;

public record ProductCreateRequest(
        @NotBlank
        @Size(max = 100)
        String productName,

        @NotNull
        @Positive
        Integer price,

        String description,

        @PositiveOrZero
        Integer displayOrder,

        Boolean autoGeneratedDescription,

        @Size(max = 500)
        String aiPromptText
) {
        public boolean shouldGenerateDescription() {
                return Boolean.TRUE.equals(autoGeneratedDescription);
        }
}
